version: "3.9"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root@100"
      POSTGRES_DB: "athon_db"
    volumes:
      - ./database/postegres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "root"
      MONGO_INITDB_DATABASE: "athonDB"
    volumes:
      - ./database/mongodb:/data/db
    ports:
      - 27017:27017
  redis:
    image: redis
    restart: always
    volumes:
    - ./datebase/redis:/usr/local/etc/redis/
    ports:
    - 6379:6379
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
